version: '3.8'

services:
  web-app:
    build: .
    container_name: defrag-web-app
    restart: unless-stopped
    network_mode: host
    environment:
      - DB_HOST=localhost
      - DB_PORT=5432
      - DB_NAME=defrag_db
      - DB_USER=defrag_user
      - DB_PASSWORD=DefragDB2024!
      - WEB_APP_PORT=8000
      - WEB_APP_HOST=0.0.0.0
      - SECRET_KEY=your-secret-key-here
      - JWT_SECRET_KEY=your-jwt-secret-key-here
      - AGENT_ID=YOUR_AGENT_ID_HERE
      - AGENT_PASSWORD=YOUR_AGENT_PASSWORD_HERE
      - CLIENT_ID=YOUR_CLIENT_ID_HERE
      - CLIENT_PASSWORD=YOUR_CLIENT_PASSWORD_HERE
      - USE_TRAINING_DB=true
      - PROPERTY_REFRESH_INTERVAL_HOURS=1
    volumes:
      - ./logs:/app/logs
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  postgres-check:
    image: postgres:15
    container_name: postgres-check
    environment:
      - POSTGRES_PASSWORD=dummy
    command: >
      sh -c "
        until pg_isready -h localhost -p 5432 -U defrag_user -d defrag_db;
        do
          echo 'Waiting for PostgreSQL...'
          sleep 2
        done
        echo 'PostgreSQL is ready!'
      "
    network_mode: host
