version: "3.8"

# Host network version for environments with networking conflicts (Tailscale, VPNs, etc.)
services:
  # RMS Defragmenter Web Application
  defrag-app:
    image: dhpsystems/rms-defragmenter:latest
    container_name: defrag-app
    restart: unless-stopped
    network_mode: host
    environment:
      - DB_HOST=localhost
      - DB_PORT=5433
      - DB_NAME=${DB_NAME:-defrag_db}
      - DB_USER=${DB_USER:-defrag_user}
      - DB_PASSWORD=${DB_PASSWORD:-DefragDB2024!}
      - SECRET_KEY=${SECRET_KEY:-your-secret-key-change-in-production}
      - JWT_SECRET_KEY=${JWT_SECRET_KEY:-your-jwt-secret-key-change-in-production}
      - AGENT_ID=${AGENT_ID}
      - AGENT_PASSWORD=${AGENT_PASSWORD}
      - CLIENT_ID=${CLIENT_ID}
      - CLIENT_PASSWORD=${CLIENT_PASSWORD}
      - USE_TRAINING_DB=${USE_TRAINING_DB:-false}
      - PROPERTY_REFRESH_INTERVAL_HOURS=${PROPERTY_REFRESH_INTERVAL_HOURS:-1}
    volumes:
      - defrag_logs:/app/logs
      - defrag_output:/app/output
    depends_on:
      postgres:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "./health_check.sh"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # PostgreSQL Database
  postgres:
    image: postgres:15-alpine
    container_name: defrag-postgres
    restart: unless-stopped
    network_mode: host
    environment:
      POSTGRES_DB: ${DB_NAME:-defrag_db}
      POSTGRES_USER: ${DB_USER:-defrag_user}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-DefragDB2024!}
      PGPORT: 5433
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER:-defrag_user} -d ${DB_NAME:-defrag_db} -p 5433"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

volumes:
  postgres_data:
    driver: local
  defrag_logs:
    driver: local
  defrag_output:
    driver: local
